sudo: required
dist: trusty
addons:
  apt:
    sources:
      - google-chrome
    packages:
      - google-chrome-stable

language: ruby
rvm:
- 2.4.1
before_script:
- bundle exec rake db:create --all
- bundle exec rake db:migrate
script:
- bundle exec rspec
services:
- postgresql
- redis-server
notifications:
  email: false
